### ISSUE TITLE
Suggestion: A minor mode to automatically save, restore, and update presets

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/fontaine#2]
Hi Prot,

Quick suggestion I thought of as I read through the manual: There could be a `fontaine-mode` that would add `fontaine-store-latest-preset` to `kill-emacs-hook`, `fontaine-restore-latest-preset` to, e.g. `after-init-hook`, and advise `enable-theme`, etc.

Thanks for your work on Fontaine!

**Comment by protesilaos** [comment]
> From: Adam Porter ***@***.***>
> Date: Tue, 12 Dec 2023 16:40:44 -0800
>
> Hi Prot,

Hello Adam,

> Quick suggestion I thought of as I read through the manual: There
> could be a `fontaine-mode` that would add
> `fontaine-store-latest-preset` to `kill-emacs-hook`,
> `fontaine-restore-latest-preset` to, e.g. `after-init-hook`, and
> advise `enable-theme`, etc.

Yes, this make sense! I will have to give it a try. Right now I use
these but a minor mode is easier:

    ;; The other side of `fontaine-restore-latest-preset'.
    (add-hook 'kill-emacs-hook #'fontaine-store-latest-preset)

    ;; Persist font configurations while switching themes.  The
    ;; `enable-theme-functions' is from Emacs 29.
    (add-hook 'enable-theme-functions #'fontaine-apply-current-preset)

> Thanks for your work on Fontaine!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Hello again! I just pushed the change for this. Thank you!

**Comment by alphapapa** [comment]
Thanks, Prot!
