### ISSUE TITLE
fontaine--set-face failing as signature of fontaine--set-face-properties has changed

### ISSUE THREAD

**Issue by akartha** [protesilaos/fontaine#5]
I kept getting a "Wrong type argument symbolp , 220" when changing fontaine presets. 

Looking into it, I think I may have isolated it to the latest commit (fb528cd) where the definition of **fontaine--set-face-attributes** has changed to include 'slant' - 
`(defun fontaine--set-face-attributes (face family &optional weight slant height frame)`

but in the function **fontaine--set-face**, it is still being called without the 'slant' value - 
```
(defun fontaine--set-face (preset face &optional frame)
  "Set font properties taken from PRESET to FACE in optional FRAME.
If FRAME is nil, apply the effect to all frames."
  (let ((properties (fontaine--get-preset-properties preset)))
    (fontaine--set-face-attributes
     face
     (or (plist-get properties (intern (format ":%s-family" face))) 'unspecified)
     (or (plist-get properties (intern (format ":%s-weight" face))) 'unspecified)
     (or (plist-get properties (intern (format ":%s-height" face))) 'unspecified)
     frame)))

```

**Comment by protesilaos** [comment]
Hello @akartha! I do not have commit `fb528cd`. At any rate, I recognise the issue you mention here. I fixed it yesterday. Can you please try again?

**Comment by akartha** [comment]
Excellent - thank you @protesilaos. I did a straight pull package and it works fine now.

**Comment by protesilaos** [comment]
> From: akartha ***@***.***>
> Date: Wed, 21 Feb 2024 20:38:30 -0800
>
> Excellent - thank you @protesilaos. I did a straight pull package and it works fine now. 

Very well!

-- 
Protesilaos Stavrou
https://protesilaos.com
