### ISSUE TITLE
Support for more face attributes (like `:width`)

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/fontaine#6]
Hi Prot,

Thanks for your update to Fontaine 2.0.  Since it now supports the `tab-bar` face, I've been trying to update my config to work with it to set these faces.  This has required me to add `tab-bar-tab` to `fontaine-faces`, so that I can set a variable-pitch font for the `tab-bar` face (affecting the `global-mode-string` as displayed in the tab bar), and a monospace font for the `tab-bar-tab*` faces.

However, for my `tab-bar-tab*` faces, I use the `:width condensed` attribute (because for the font I use, NK57 Monospace, it's too wide at normal width), but Fontaine doesn't seem to offer support for the `:width` attribute.  So this requires me to remove `tab-bar` from `fontaine-faces` so as to remove it from Fontaine's purview.

Could support for `:width` (and perhaps other attributes) be added to Fontaine?

**Comment by protesilaos** [comment]
Hello Adam! I just added this. Thank you!

**Comment by alphapapa** [comment]
Hi Prot, thank you very much!
